# About the project

*After completing this course you will understand the principles and advantages of using open research tools with open data and understand the possibilities of reproducible research. You will know how to use R, RStudio, RMarkdown, and GitHub for these tasks and also know how to learn more of these open software tools. You will also know how to apply certain statistical methods of data science, that is, data-driven statistics.*

GitHub Repository: <https://github.com/emilia-2022/IODS-project.git>

## Reflection 1

```{r}
date()

```

*Open the file chapter1.Rmd located in your IODS-project folder with **RStudio**. Just write some of your thoughts about this course freely in the file, e.g., How are you feeling right now? What do you expect to learn? Where did you hear about the course?*

Currently, I am feeling a little overwhelmed as I have never worked with Github and had some technical issues while setting up the course templates. I also have very little experience with R and my first time working with it was during a course last period. So, overall I feel a bit overwhelmed but trying to stay positive!

Having heard about the course through our social data science teacher tutor, I expect to learn more about the world of open data science. I also hope to learn how to effectively use Github to improve my workflow and implement version control in my future projects. \
\
*Also reflect on your learning experiences with the **R for Health Data Science** book and the **Exercise Set 1**:How did it work as a "crash course" on modern R tools and using RStudio? Which were your favorite topics? Which topics were most difficult? Some other comments on the book and our new approach of
getting started with R Markdown etc.?*

I found that Exercise Set 1 worked well as a crash course for R. It was also similar to the course material presented in my previous R course which helped me understand the content more clearly. I find the book to be well written and all the comments in the provided R code really help my learning! However, it is a lot of material to cover in a week if you are not familiar with R and R Markdown.

One of the concepts I still struggle with is long versus wide data formats. It was briefly touched on during a previous course but I am still not sure how and when to apply it in my own work. Another concept I still struggle to interpret clearly is the residual graphs. I understand - in theory - what they are supposed to look like but I find it hard to interpret them when they differ from the perfect model.

My favourite topics were located under *Chapter 4: Different types of plots.* I really enjoy how versatile R is and how many ways there are to work data visualizations. I especially liked how you are able to customize your plots using various commands in R.
